project:
  type: book
  output-dir: docs

book:
  title: "Estimativa do custo dos sinistros de trânsito no estado de São Paulo - Metodologia de cálculo"
  subtitle: "Nota Técnica 02 - v3.0"
  # author:
  #   - name: Departamento Estadual de Trânsito de São Paulo (Detran-SP)
  #   - name: Diretoria de Segurança Viária
  #   - name: Coordenadoria Geral de Segurança Viária
  #   - name: Coordenadoria do Observatório de Segurança no Trânsito
  #   - name: Divisão de Estudos para Segurança no Trânsito
  #     email: estudos.transito@detran.sp.gov.br
  #   - name: Divisão de Estatísticas de Trânsito
  date: last-modified
  chapters:
    - index.qmd
    - 01-introducao.qmd
    - 02-metodologia.qmd
    - 03-resultados.qmd
    - 04-conclusao.qmd
    - 05-referencias.qmd

format:
  html:
    lang: pt-BR
    toc: true
    toc-depth: 4
    #fig-align: center
    cap-location: top
    fig-height: 5
    fig-width: 8
    fig-dpi: 300
    code-links:  
      - text: Repositório      
        icon: github      
        href: "https://github.com/detran-sp/custos_sinistros_sp"
    embed-resources: true

execute: 
  warning: false
  message: false
  echo: false

number-sections: true

bibliography: refs.bib

